import streamlit as st

st.title("港幣兌換澳元")
st.number_input("港幣", value=200000, step=1, key="hkd")
l, r = st.columns(2)
l.number_input("賣出價1", value=4.9695, key="selling_price1")
r.number_input("賣出價2", value=4.9798, key="selling_price2")
aud1 = round(st.session_state.hkd/st.session_state.selling_price1, 4)
aud2 = round(st.session_state.hkd/st.session_state.selling_price2, 4)
l.write(f"兌換澳幣1: {aud1}")
r.write(f"兌換澳幣2: {aud2}")

st.number_input("定期日數", value=7, step=1, key="aud_days")
l, r = st.columns(2)
l.number_input("利率1", value=0.15, step=0.01, key="aud_interest_rate1")
r.number_input("利率2", value=12.8, step=0.01, key="aud_interest_rate2")
interest1 = round(aud1*(st.session_state.aud_interest_rate1/100)*(st.session_state.aud_days/365), 4)
interest2 = round(aud2*(st.session_state.aud_interest_rate2/100)*(st.session_state.aud_days/365), 4)
l.write(f"獲得利息1: {interest1}")
r.write(f"獲得利息2: {interest2}")
total1 = round(aud1 + interest1, 4)
total2 = round(aud2 + interest2, 4)
if total1 > total2:
    l.markdown(f"總數1: <span style='color: red;'>{total1}</span>", unsafe_allow_html=True)
    r.markdown(f"總數2: {total2}")
else:
    l.markdown(f"總數1: {total1}")
    r.markdown(f"總數2: <span style='color: red;'>{total2}</span>", unsafe_allow_html=True)

st.divider()

st.title("澳元兌換港幣")
st.number_input("澳幣", value=1000, step=1, key="aud")
l, r = st.columns(2)
l.number_input("買入價1", value=5.0005, key="buying_price1")
r.number_input("買入價2", value=5.0108, key="buying_price2")
hkd1 = round(st.session_state.aud*st.session_state.buying_price1, 4)
hkd2 = round(st.session_state.aud*st.session_state.buying_price2, 4)
l.write(f"兌換港幣1: {hkd1}")
r.write(f"兌換港幣2: {hkd2}")

st.number_input("定期日數", value=7, step=1, key="hkd_days")
l, r = st.columns(2)
l.number_input("利率1", value=0.15, step=0.01, key="hkd_interest_rate1")
r.number_input("利率2", value=12.8, step=0.01, key="hkd_interest_rate2")
interest1 = round(hkd1*(st.session_state.hkd_interest_rate1/100)*(st.session_state.hkd_days/365), 4)
interest2 = round(hkd2*(st.session_state.hkd_interest_rate2/100)*(st.session_state.hkd_days/365), 4)
l.write(f"獲得利息1: {interest1}")
r.write(f"獲得利息2: {interest2}")
total1 = round(hkd1 + interest1, 4)
total2 = round(hkd2 + interest2, 4)
if total1 > total2:
    l.markdown(f"總數1: <span style='color: red;'>{total1}</span>", unsafe_allow_html=True)
    r.markdown(f"總數2: {total2}")
else:
    l.markdown(f"總數1: {total1}")
    r.markdown(f"總數2: <span style='color: red;'>{total2}</span>", unsafe_allow_html=True)