[project]
name = "currencyexchange"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymongo[srv]==3.12",
    "streamlit>=1.44.1",
]
